### ISSUE TITLE
DB 서버 구성하기

### ISSUE THREAD

**Issue by bearics** [juniors-dev-study/domain-driven-design#25]
DB랑 secrets 설정하기
스키마 sql 도 저장하기

**Comment by bearics** [comment]
DB랑 secrets 설정하기

**Comment by bearics** [comment]
MYSQL DB 서버
jdbc:mysql://ddd.cu3ry11okp5j.us-east-2.rds.amazonaws.com:3306

아이디 비번은 따로 공유

**Comment by bearics** [comment]
```
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt large secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.DB_PW }}
```

위와 같이 actions에서 불러서 사용 가능.
